public class integerPrimitives{

    public integerPrimitives() {

    }


    public integerPrimitives(ApexPages.StandardController controller) {

    }
    
    public PageReference action(){
        variableX= variableX + variableX;

        int();
        return null;
        
    }
    
    public integer variableX{get;set;}
    public integer i{get;set;}
    
    public static Void int(){
        integer i=10;
    }

}